name: Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/install@v3

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --repo=$GITHUB_REPOSITORY \
            --title=${{ github.ref_name }} \
            --generate-notes || true

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT: ${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        run: |
          tar zcvf $ARTIFACT -C build aws-cost-sankey
          gh release upload ${{ github.ref_name }} $ARTIFACT
